# Generated by Django 4.0.4 on 2022-05-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('value', models.CharField(max_length=200)),
                ('cmdfromapp', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('value', models.CharField(max_length=200)),
                ('cmdfromapp', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='presion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
