# Generated by Django 4.0.4 on 2022-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vanne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('value', models.CharField(max_length=200)),
                ('cmdfromapp', models.CharField(max_length=2)),
            ],
        ),
    ]
