# Generated by Django 2.2.4 on 2022-04-27 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0003_auto_20220427_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presion',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
