# Generated by Django 2.2.4 on 2022-04-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0004_auto_20220427_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='motor',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='msg',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='presion',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
