# Generated by Django 2.2.4 on 2022-04-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0005_auto_20220427_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presion',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
