# Generated by Django 2.2.4 on 2022-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0006_auto_20220427_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presion',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
