# Generated by Django 4.0.4 on 2022-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0008_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='cmdfromapp',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
