# Generated by Django 4.0.4 on 2022-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MqttApp', '0009_motor_cmdfromapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cmdfromapp',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
