# Generated by Django 4.0.4 on 2022-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(default='technicien', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
